### ISSUE TITLE
Document `pin.pull` functionality

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/t2-docs#93]
@dudleyjosh noticed that the `pin.pull(mode)` functionality is currently undocumented (Reference -> https://tessel.gitbooks.io/t2-docs/content/API/Hardware_API.html). 

Documentation and examples for using this method could go under the "Pin mapping" section, where it is explained that "by default, all of the pins are pulled high if not specifically set". 

I think it would be nice to match the structure of the [Pin Interrupts docs](https://tessel.io/docs/hardwareAPI#interrupt-pins):
- [ ] add a working [Fritzing](http://fritzing.org/home/) example to match the code sample (maybe with a button)
- [ ] add a "Usage" section that describes what values `pull` takes as arguments (see the Interrupts usage section as an example)

Check out the `t2-firmware` source for more info about how each method works:
- [`pull`](https://github.com/tessel/t2-firmware/blob/master/node/tessel-export.js#L737-L758)

Feel free to mention me in this issue, or a PR, or post in [Tessel Slack #community channel](https://tessel-slack.herokuapp.com/) with question or if review is needed.

**Comment by mittalshravika** [comment]
Brihi and I (members of 276linesofCode) have started working on this issue.

We were trying to explain the `pin.pull(mode)` command using an example with a push button. For the same, we were thinking of linking the code with a fritzing diagram of the same.

Could you let us know where to put the fritzing diagram because we could not find any other in the t2-docs to refer to as an example for the same.
